### ISSUE TITLE
 Not working on the free Dutch variant

### ISSUE THREAD

**Issue by Droidphilev** [Unbrick/QuizduellXposed#1]
Sadly enough the app hangs at "loading" when the module is enabled.

**Comment by Unbrick** [comment]
Can you provide a stacktrace or some more details?

**Comment by Droidphilev** [comment]
I expected this :(
The problem is that i'm just a noob user. I don't even know what a stacktrace is TBH. I'm sorry for that :(

**Comment by Unbrick** [comment]
Have you tried clearing your apps data?

**Comment by Droidphilev** [comment]
I'm so sorry to have wasted your time. I Uninstalled the app and after reinstall it works!. Thanks you!

A request that is probably not allowed: is it possible that you app disables the timed ads in the free version? I guess not

**Comment by Droidphilev** [comment]
small update: it works fine on the free version but not on the premium one it seems (installed in exact the same way.

**Comment by Unbrick** [comment]
Did you do a soft-reboot before you tried the premium version?

**Comment by Droidphilev** [comment]
nop, will try that and report back

**Comment by Unbrick** [comment]
Okay, thank you. I can try to disable the ads. No guaranteed success.

**Comment by Droidphilev** [comment]
after a reboot it doesn't work on premium

**Comment by Unbrick** [comment]
On which version of premium are you? I'm currently testing with the latest (v.3.1.4) german versions of free and premium. For me are both working as expected.

**Comment by Droidphilev** [comment]
it seems to be 2.0.2 (found it online). Maybe better forgot this as it is much much older it seems

**Comment by Unbrick** [comment]
Oh well i can imagine your problem. Try updating to the latest version, then it should work!

**Comment by Droidphilev** [comment]
will, take a look, thx!
