### ISSUE TITLE
funktioniert leider nicht mehr

### ISSUE THREAD

**Issue by donedone1** [Unbrick/QuizduellXposed#10]
Hallo,
tolle App-Tipps auf Deiner Seite (Osmand, etc.).
Habe gestern  auf meinem gerootetem Samsung das QuizduellHook aktiviert.
Leider funktioniert es nicht mehr.
Wahrscheinlich liegt es an der mittlerweile höheren Quizduell-Version, oder?
Danke für Deine Mühe.
VG

**Comment by Unbrick** [comment]
Moin,

darf ich fragen was du mit meiner Seite meinst, eigentlich hab ich im Moment keine.

Welche QD Version hast du denn verwendet?

Viele Grüße

**Comment by Unbrick** [comment]
Habe jetzt Testberichte von den Versionen 4.4.5 und 4.4.9,(danke an Schlepptop) beide funktionieren wie sie es sollten. Es ist nicht geplant ältere Versionen zu unterstützen, ich schließe den Issue daher.

**Comment by donedone1** [comment]
Hallo Unbrick,
danke für deine Antwort.
Sorry, habe nicht Deine Seite gemeint.
Funktioniert bei mir leider immer noch nicht.
Weiß nicht was ich falsch mache:
Meine Daten:
Samsung Galaxy S3 Stock Rom (Kitkat)
Gerootet (Super SU free 2.8.2)
Vorgehensweise:
Xposed Framework Installer (2.7 experimental 1) installiert
Aktuelle QD-Version aus Playstore installiert.
QD-Hook installiert und in Xposed aktiviert.
Der Haken erscheint nach Softstart leider nicht.
Vielleicht hast Du eine Idee?
Danke und VG
donedone1
