### ISSUE TITLE
funktioniert bei mir leider nicht...

### ISSUE THREAD

**Issue by donedone1** [Unbrick/QuizduellXposed#11]
Hallo Unbrick,
danke für deine Antwort.
Sorry, habe nicht Deine Seite gemeint.
Funktioniert bei mir leider immer noch nicht.
Weiß nicht was ich falsch mache.
Meine Daten:
Samsung Galaxy S3 Stock Rom (Kitkat)
Gerootet (Super SU free 2.8.2)
Vorgehensweise:
Xposed Framework Installer (2.7 experimental 1) installiert
Aktuelle QD-Version aus Playstore installiert.
QD-Hook installiert und in Xposed aktiviert.
Der Haken erscheint nach Softstart leider nicht.
Vielleicht hast Du eine Idee, was ich falsch gemacht haben könnte?
Danke und VG
donedone1

**Comment by Unbrick** [comment]
Hallo donedone1, 
Die Version die ich noch bräuchte ist deine Quizduell Version. Die aktuellste QD Version hängt immer von deinem Gerät und deiner Android Version ab, daher weiß ich nicht was die aktuellste für dich ist.

Viele Grüße

Unbrick

Edit: Außerdem wäre der Xposed-Log sehr praktisch, diesen findest du im Xposed-Installer links im NavigationDrawer unter dem bereich Log.

**Comment by donedone1** [comment]
Hallo Unbrick,

habe die Version 4.4.9 installiert.
Die Log-Datei läßt sich aus Xposed nicht extrahieren, obwohl bei Logs: "Logs des Xposed Frameworks ansehen, speichern und senden" steht.

Kurzer Auszug von Hand:
"Loading modules from /data/app/de.qdxposed-1.apk
Loading class de.qdxposed.Hook
de.robv.android.xposed.XposedHelpers$ClassNotFoundError:java.lang.ClassNotFoundException: se.feomedia.quizkampen.act.game.AlternativeButtons
 at de.robv.android.xposed.Xposed...."

Vielleicht geht es mit dem Xposed (2.7 experimental 1) nicht...
Das Xposed 3.1.4 läßt sich leider nicht installieren  - liegt am ROM!
Habe heute schon mal ein LineageOS draufgemacht. Hier machen allerdings die GApps Probleme....

Ich versuchs weiter und melde mich nächste Woche wieder...
Hast Du noch eine Idee?

Danke und VG
donedone1

**Comment by Unbrick** [comment]
Hallo donedone1,

die Version 4.4.9 sollte eigentlich gehen. Der Log macht mich etwas stutzig da die Klasse in der Version definitiv existieren sollte. Verwendest du die Premium oder die Lite Version von Quizduell?

Um dir wirklich weiterzuhelfen bräuchte ich den vollständigen Xposed-Log. 

Viele Grüße

Unbrick

**Comment by donedone1** [comment]
Hallo Unbrick,
habe es jetzt auf meinem HTC installiert.
Hier funktioniert es einwandfrei.
Vielen Dank
donedone1

**Comment by Unbrick** [comment]
Hallo donedone1,

alles klar, vielen Dank für deine Rückmeldung!

Viele Grüße

Unbrick
