### ISSUE TITLE
[IMPROVEMENT/QUESTION] ARD Quiz

### ISSUE THREAD

**Issue by dillasyx** [Unbrick/QuizduellXposed#13]
Couldn't test it today. In germany we have a tv show using Quizduell in their own app, is it possible to use this module there too? Else is it possible to port it?

**Comment by dillasyx** [comment]
EDIT: app is called ARD Quiz

**Comment by Unbrick** [comment]
Hi nidico100,

sorry for my late response. If the internal structure of the both apps are identical it shouldn't be a problem. I'll dig into this these days.

**Comment by Unbrick** [comment]
Hi @nidico100 

i just looked into the ARD Quiz application but only the look and feel is simmilar to Quizduell but is from a entirely different developer which results in a different internal structure, porting would take quite a lot of time.
