### ISSUE TITLE
Dont work

### ISSUE THREAD

**Issue by BoBBer446** [Unbrick/QuizduellXposed#14]
Current Version dosent Work and Show No icon

**Comment by liftedsource** [comment]
Same problem here.

OnePlus 5T
Android 8.1
Magisk 16.3
Xposed Version 90-beta3

Xposed Log with only QuizduellHook:

03-27 18:00:58.132 I/Xposed  (  690): -----------------
03-27 18:00:58.132 I/Xposed  (  690): Starting Xposed version 90-beta3, compiled for SDK 27
03-27 18:00:58.132 I/Xposed  (  690): Device: ONEPLUS A5010 (OnePlus), Android version 8.1.0 (SDK 27)
03-27 18:00:58.132 I/Xposed  (  690): ROM: ONEPLUS A5010_43_180411
03-27 18:00:58.132 I/Xposed  (  690): Build fingerprint: OnePlus/OnePlus5T/OnePlus5T:8.1.0/OPM1.171019.011/04110359:user/release-keys
03-27 18:00:58.132 I/Xposed  (  690): Platform: arm64-v8a, 64-bit binary, system server: yes
03-27 18:00:58.132 I/Xposed  (  690): SELinux enabled: yes, enforcing: yes
03-27 18:00:58.143 I/Xposed  (  690): -----------------
03-27 18:00:58.143 I/Xposed  (  690): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
03-27 18:00:58.625 E/Xposed  (  690): Unable to open /vendor/framework/oat/arm64 to prepare apps for Xposed: Permission denied
04-26 04:13:08.977 I/Xposed  (  690): Detected ART runtime
04-26 04:13:08.979 I/Xposed  (  690): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
04-26 04:13:09.236 I/Xposed  (  690): Loading modules from /data/app/de.qdxposed-8lS7uFT1V1fF83bi7PR2eA==/base.apk
04-26 04:13:09.242 I/Xposed  (  690):   Loading class de.qdxposed.Hook
04-26 04:13:17.280 I/Xposed  (  691): -----------------
04-26 04:13:17.280 I/Xposed  (  691): Starting Xposed version 90-beta3, compiled for SDK 27
04-26 04:13:17.280 I/Xposed  (  691): Device: ONEPLUS A5010 (OnePlus), Android version 8.1.0 (SDK 27)
04-26 04:13:17.280 I/Xposed  (  691): ROM: ONEPLUS A5010_43_180411
04-26 04:13:17.280 I/Xposed  (  691): Build fingerprint: OnePlus/OnePlus5T/OnePlus5T:8.1.0/OPM1.171019.011/04110359:user/release-keys
04-26 04:13:17.280 I/Xposed  (  691): Platform: arm64-v8a, 32-bit binary, system server: no
04-26 04:13:17.280 I/Xposed  (  691): SELinux enabled: yes, enforcing: yes
04-26 04:13:17.282 I/Xposed  (  691): -----------------
04-26 04:13:17.282 I/Xposed  (  691): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
04-26 04:13:17.431 E/Xposed  (  691): Unable to open /vendor/framework/oat/arm to prepare apps for Xposed: Permission denied
04-26 04:13:17.969 I/Xposed  (  691): Detected ART runtime
04-26 04:13:17.970 I/Xposed  (  691): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
04-26 04:13:18.145 I/Xposed  (  691): Loading modules from /data/app/de.qdxposed-8lS7uFT1V1fF83bi7PR2eA==/base.apk
04-26 04:13:18.232 I/Xposed  (  691):   Loading class de.qdxposed.Hook

**Comment by BoBBer446** [comment]
Yes its 8.1

**Comment by Unbrick** [comment]
Hey guys, 

I just checked and got the same problem (at least I think so).

@liftedsource Is it possible that you stripped some parts of your log out? I'm getting a classnotfound exception while your Xposed log looks fine :smile: . Otherwise, is it possible that you didn't start QD before copying the log? The error which occurs for me is a runtime error and is issued on starting QD.

@BoBBer446  The application is not intended to show a icon as I haven't included any UI or settings.

I'll dig into this in the next few days, for me it looks like they changed some internal structures of the app which breaks the functionality.

**Comment by Unbrick** [comment]
Just to report back: A few internal structures changed (class and package names). I updated the module (to v.1.3) to match the Quizduell update, should now work on old and new QD versions!

Thanks for your bug report guys!
