### ISSUE TITLE
Only working after soft reboot

### ISSUE THREAD

**Issue by Droidphilev** [Unbrick/QuizduellXposed#3]
Hi again

Removed ads working fine thanks!

I wonder why it only works after a soft reboot. After a full reboot the app keeps on "loading". After a reboot i have to soft reboot every time to make it work again.

**Comment by Unbrick** [comment]
I cant really figure out where your problem now could be. But it sounds for me like your xposed installation isnt working properly. Try flashing xposed again!

**Comment by Droidphilev** [comment]
Hi,

Xposed works just fine, that's not the problem (using it for years and i know how it works). I have several modules installed that would notify me if Xposed wasn't working/enabled. Xprivacy is a good example of an app that checks for a working Xposed. I can only tell that after a normal reboot if i open Quizduel it keeps on "loading" (which proves that your module is enabled otherwise Quizduel would load fine and there would be no 'tick' after the answers. I have tried this: disable QuizduellXposed and reboot normal. Quizduel works fine then). If i softreboot afterwards it works again. It can be rom related, i have no idea. It's not a very big deal as it works as long as i softreboot after a normal reboot, that's all.

**Comment by Unbrick** [comment]
Sounds weired. Which rom are you on? And which version of Quizduell? I'm courious whether the dutch version has only one classes.dex.

**Comment by Droidphilev** [comment]
Hi,

I use Beanstalk M 6.0.1 (CM based) and the versionof QD i use is 4.0.0

**Comment by Unbrick** [comment]
So i just looked into QD 4.0.0, dutch version but i can't find any differences in the methods. So i assume it's rom realated.

**Comment by Droidphilev** [comment]
Hi again,

I'm so sorry for replying with delay (party hard you know). I just bough a new device and on this device at works fine after a normal boot so i guess it is indeed rom related.

**Comment by Unbrick** [comment]
Thank you for your response, so i dont have to worry anymore about incompability
