### ISSUE TITLE
Quiz of kings(persian variant)

### ISSUE THREAD

**Issue by chriskhany** [Unbrick/QuizduellXposed#4]
Hi.i tried the persian variant (called quiz of kings available in Google play)and unfortunately it doesn't work.could u please fix it?

**Comment by Unbrick** [comment]
Quiz of Kings sadly isn't the persian variant of Quizduell, its just a simmilar looking app by another developer. All original quizduell apps are published by FEO Media AG. Quiz of Kings is published by Elyas Nadali. 

I just took a quick look into QoK, the app is developed using dagger and has a entirely different directory structure. Sadly i don't speak any persian, nor i'm able to read it so developing a xposed module for QoK would be too hard.

**Comment by chriskhany** [comment]
Hi so is it possible if I translate quiz of kings?(I can do this one!if it's the app interface that u need)or could u please teach me how u made it so that I make it for this one?

**Comment by Unbrick** [comment]
I just took a deeper look into it. Quiz of Kings is developed using Corona, a multi-platform-sdk. So the code (strangely enough) is written in Lua-Script. Quite difficult to figure out where anything is located and how the app exactly works.

**Comment by chriskhany** [comment]
I see....so could u please help me?I pretty much don't know where to start!throw at me all the guides and stuff I need to know!I'm really strong wielded to do this!hard or easy its sure worth a shot.and for any noob there's a start!please!(if there's something I want to but can't have or others can't or wouldn't provide for me I should achieve it myself.am I wrong??oh inorder not to spam this place I messaged u at xda.thanks!love you!😊
