### ISSUE TITLE
Not hooking on Quizduell premium

### ISSUE THREAD

**Issue by MisfortuneNeko** [Unbrick/QuizduellXposed#8]
Hi, I'm currently playing on Quizduello ver 2.1.5, italian version, and it's not hooking the answers. Tested on Quizduell german version and works fine. Thanks!

**Comment by Unbrick** [comment]
I'm very sorry to say that hooking Quizduell version 2.1.5 (no matter on which languange) is nearly impossible. 
Just took a look at it, it is more than extremly obfuscated so it's damn hard to reverse. 

The only workaround would be using version 4.x.x. Sorry about that!

**Comment by MisfortuneNeko** [comment]
Both free and premium italian version are 2.1.5. Thank you very much for your answer and great job with this Xposed module!
